[build]
builder = "nixpacks"

[phases.setup]
nixPkgs = [
  "python311",         # Main Python environment
  "tesseract",         # For OCR
  "poppler_utils"      # For pdf2image
]

[phases.install]
cmds = [
  "python -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "streamlit run src/streamlit_app.py --server.port=$PORT --server.address=0.0.0.0"
